### ISSUE TITLE
Penyesuaian Tampilan Home section "Dipercaya Oleh"

### ISSUE THREAD

**Issue by reza21** [creasico/creasico.github.io#10]
### Describe the Updated

Guna penyesuaian tampilan, bagian ini judulnya diganti `Client & Partner`. Kemudian masukkan beberapa client dan partner kita, diantaranya:

- Infimedia
- Telkom Indonesia
- STN Ready Mix
- Ponpes Al Fusha

![image](https://github.com/creasico/creasico.github.io/assets/10904393/7d40f2c7-1759-4a23-8999-9b49549efc85)

**Comment by feryardiant** [comment]
Note: itu pake translasi ya

**Comment by alvinathoriqoh** [comment]
> Note: itu pake translasi ya

ini disesuaikan translasi atau tidak pak?
<img width="947" alt="nkajsna" src="https://github.com/creasico/creasico.github.io/assets/117893652/337279c9-1592-421a-8ec3-b7a0374e0523">

**Comment by feryardiant** [comment]
> ini disesuaikan translasi atau tidak pak?

Stick ke task nya pak @reza21 aja, yg itu bisa diabaikan dulu.
