### ISSUE TITLE
Penggunaan Iconify sebagai default icon

### ISSUE THREAD

**Issue by feryardiant** [creasico/creasico.github.io#7]
### Clear and concise description of the task

URL : https://iconify.design
GitHub : https://github.com/iconify/iconify

Iconify merupakan icon framework berbasis svg dan bisa dipakai di hampir semua web framework, terdapat ratusan icon set yang dapat digunakan menyesuaikan kebutuhan projek.

### Suggested solution

Dalam hal ini saya usul untuk menggunakan `feather` icon sebagai default icon set utama untuk project ini.

### Alternative

Ada usulan?

---

### Before submitting the issue, please make sure you do the following 

- [x] Read the [Contributing Guidelines](https://github.com/creasico/.github/blob/master/CONTRIBUTING.md).
- [x] Provide a description in this issue that describes the bug.

**Comment by mrofi** [comment]
Baru lihat iconify, sepertinya keren. Gas 🔥
